apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cyclecloud.fullname" . }}
  labels:
    {{- include "cyclecloud.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: premium-disk
  resources:
    requests:
      storage: {{ .Values.cycle.dataDiskSize }}
