nameOverride: ""
fullnameOverride: ""

azureIdentity:
  resourceID: /subscriptions/%SUBSCRIPTION_ID%/resourcegroups/cc-aks-tf-nodes-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/cc-aks-tf-ui
  clientID: 123

cycle:
  replicas: 1
  dataDiskSize: 128Gi
  backupsDiskSize: 128Gi
  
  uid: 1169
  gid: 1169
  username: cc_admin
  password: 
  webServerHostname: 
  webServerPort: 8080
  webServerSslPort: 8443
  webServerClusterPort: 9443
  configureDefaultAccount: true
  storage: 123
  userPubKey: 123
  resourceGroup: 123
  containerImage: 123

service:
  type: LoadBalancer
  port: 443

